### ISSUE TITLE
Frequency map agent integration test is failing with new-profile branch

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1537]
The test is updated to use the raw report new test pattern with this PR here:
https://github.com/geopm/geopm/pull/1536

This test will pass with the dev branch, but fail with the new-profile branch.  

```
======================================================================
FAIL: test_agent_frequency_map (__main__.TestIntegration_frequency_map)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cmcantal/Git/geopm/integration/test/test_frequency_map.py", line 143, in test_agent_frequency_map
    util.assertNear(self, expect, actual, msg=msg)
  File "/home/cmcantal/Git/geopm/integration/test/util.py", line 285, in assertNear
    self.fail('The fractional difference between {a} and {b} is greater than {epsilon}.  {msg}'.format(a=a, b=b, epsilon=epsilon, msg=msg))
AssertionError: The fractional difference between 1000000000.0 and 1112660000.0 is greater than 0.05.  all2all: frequency should be near assigned map frequency

----------------------------------------------------------------------
```

The all2all region frequency is off compared to the value in the policy (~1.1GHz actual vs 1.0GHz requested).  This issue consistently reproduces.

The report from running that test with the dev branch:

```
GEOPM Version: 1.1.0+dev778g146572d
Start Time: Mon Feb 08 16:36:51 2021
Profile: test_frequency_map
Agent: frequency_map
Policy: {"FREQ_DEFAULT": 2101000000, "FREQ_UNCORE": "NAN", "HASH_0": 2806759221, "FREQ_0": 1200000000, "HASH_1": 3599882752, "FREQ_1": 1900000000, "HASH_2": 1037861311, "FREQ_2": 1000000000, "HASH_3": "NAN", "FREQ_3": "NAN", "HASH_4": "NAN", "FREQ_4": "NAN", "HASH_5": "NAN", "FREQ_5": "NAN", "HASH_6": "NAN", "FREQ_6": "NAN", "HASH_7": "NAN", "FREQ_7": "NAN", "HASH_8": "NAN", "FREQ_8": "NAN", "HASH_9": "NAN", "FREQ_9": "NAN", "HASH_10": "NAN", "FREQ_10": "NAN", "HASH_11": "NAN", "FREQ_11": "NAN", "HASH_12": "NAN", "FREQ_12": "NAN", "HASH_13": "NAN", "FREQ_13": "NAN", "HASH_14": "NAN", "FREQ_14": "NAN", "HASH_15": "NAN", "FREQ_15": "NAN", "HASH_16": "NAN", "FREQ_16": "NAN", "HASH_17": "NAN", "FREQ_17": "NAN", "HASH_18": "NAN", "FREQ_18": "NAN", "HASH_19": "NAN", "FREQ_19": "NAN", "HASH_20": "NAN", "FREQ_20": "NAN", "HASH_21": "NAN", "FREQ_21": "NAN", "HASH_22": "NAN", "FREQ_22": "NAN", "HASH_23": "NAN", "FREQ_23": "NAN", "HASH_24": "NAN", "FREQ_24": "NAN", "HASH_25": "NAN", "FREQ_25": "NAN", "HASH_26": "NAN", "FREQ_26": "NAN", "HASH_27": "NAN", "FREQ_27": "NAN", "HASH_28": "NAN", "FREQ_28": "NAN", "HASH_29": "NAN", "FREQ_29": "NAN", "HASH_30": "NAN", "FREQ_30": "NAN"}

Hosts:
  mcfly2:
    Frequency map:
      0x3ddc81bf: 1.0000000000000000e+09
      0xa74bbf35: 1.2000000000000000e+09
      0xd691da00: 1.9000000000000000e+09
      0x644f9787: 2.1010000000000000e+09
      0x725e8066: 2.1010000000000000e+09
      0x7b561f45: 2.1010000000000000e+09
      0xd13bd34f: 2.1010000000000000e+09
      0xdcd03752: 2.1010000000000000e+09

    Regions:
    -
      region: "all2all"
      hash: 0x3ddc81bf
      runtime (s): 6.27815
      sync-runtime (s): 5.06244
      package-energy (J): 556.523
      dram-energy (J): 66.3857
      power (W): 109.932
      frequency (%): 47.7253
      frequency (Hz): 1.00223e+09
      time-hint-network (s): 6.27677
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 5
      frequency-map: 1000000000.000000
    -
      region: "dgemm"
      hash: 0xa74bbf35
      runtime (s): 3.55531
      sync-runtime (s): 2.52607
      package-energy (J): 387.068
      dram-energy (J): 39.2645
      power (W): 153.229
      frequency (%): 57.0972
      frequency (Hz): 1.19904e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 5
      frequency-map: 1200000000.000000
    -
      region: "stream"
      hash: 0xd691da00
      runtime (s): 2.61525
      sync-runtime (s): 1.84307
      package-energy (J): 358.884
      dram-energy (J): 52.9094
      power (W): 194.72
      frequency (%): 90.4415
      frequency (Hz): 1.89927e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 5
      frequency-map: 1900000000.000000
    -
      region: "model-init"
      hash: 0x644f9787
      runtime (s): 1.82535
      sync-runtime (s): 1.77936
      package-energy (J): 370.45
      dram-energy (J): 48.063
      power (W): 208.193
      frequency (%): 99.9984
      frequency (Hz): 2.09997e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 1
      frequency-map: 2101000000.000000
    -
      region: "MPI_Barrier"
      hash: 0x7b561f45
      runtime (s): 0.679653
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0.679653
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 5
      frequency-map: 2101000000.000000
    -
      region: "geopm_stream_model_region_startup"
      hash: 0xdcd03752
      runtime (s): 0.0542394
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 1
      frequency-map: 2101000000.000000
    -
      region: "geopm_dgemm_model_region_startup"
      hash: 0xd13bd34f
      runtime (s): 0.00240818
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 1
      frequency-map: 2101000000.000000
    Unmarked Totals:
      runtime (s): 0.520302
      sync-runtime (s): 3.82979
      package-energy (J): 650.243
      dram-energy (J): 71.0246
      power (W): 169.786
      frequency (%): 87.7909
      frequency (Hz): 1.84361e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 0
      frequency-map: 2101000000.000000
    Epoch Totals:
      runtime (s): 13.2094
      sync-runtime (s): 13.1354
      package-energy (J): 1932.87
      dram-energy (J): 227.925
      power (W): 147.15
      frequency (%): 72.318
      frequency (Hz): 1.51868e+09
      time-hint-network (s): 6.95643
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      count: 5
      time-hint-ignore (s): 0.0566476
    Application Totals:
      runtime (s): 15.0407
      sync-runtime (s): 15.0407
      package-energy (J): 2323.17
      dram-energy (J): 277.647
      power (W): 154.458
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 6.95643
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      time-hint-ignore (s): 0.0566476
      geopmctl memory HWM (B): 56385536
      geopmctl network BW (B/sec): 0
```

and from the new-profile branch:
```
GEOPM Version: 1.1.0+dev935g55c4399
Start Time: Mon Feb 08 16:48:45 2021
Profile: test_frequency_map
Agent: frequency_map
Policy: {"FREQ_DEFAULT": 2101000000, "FREQ_UNCORE": "NAN", "HASH_0": 2806759221, "FREQ_0": 1200000000, "HASH_1": 3599882752, "FREQ_1": 1900000000, "HASH_2": 1037861311, "FREQ_2": 1000000000, "HASH_3": "NAN", "FREQ_3": "NAN", "HASH_4": "NAN", "FREQ_4": "NAN", "HASH_5": "NAN", "FREQ_5": "NAN", "HASH_6": "NAN", "FREQ_6": "NAN", "HASH_7": "NAN", "FREQ_7": "NAN", "HASH_8": "NAN", "FREQ_8": "NAN", "HASH_9": "NAN", "FREQ_9": "NAN", "HASH_10": "NAN", "FREQ_10": "NAN", "HASH_11": "NAN", "FREQ_11": "NAN", "HASH_12": "NAN", "FREQ_12": "NAN", "HASH_13": "NAN", "FREQ_13": "NAN", "HASH_14": "NAN", "FREQ_14": "NAN", "HASH_15": "NAN", "FREQ_15": "NAN", "HASH_16": "NAN", "FREQ_16": "NAN", "HASH_17": "NAN", "FREQ_17": "NAN", "HASH_18": "NAN", "FREQ_18": "NAN", "HASH_19": "NAN", "FREQ_19": "NAN", "HASH_20": "NAN", "FREQ_20": "NAN", "HASH_21": "NAN", "FREQ_21": "NAN", "HASH_22": "NAN", "FREQ_22": "NAN", "HASH_23": "NAN", "FREQ_23": "NAN", "HASH_24": "NAN", "FREQ_24": "NAN", "HASH_25": "NAN", "FREQ_25": "NAN", "HASH_26": "NAN", "FREQ_26": "NAN", "HASH_27": "NAN", "FREQ_27": "NAN", "HASH_28": "NAN", "FREQ_28": "NAN", "HASH_29": "NAN", "FREQ_29": "NAN", "HASH_30": "NAN", "FREQ_30": "NAN"}

Hosts:
  mcfly6:
    Frequency map: 
    0x000000003ddc81bf: 1.0000000000000000e+09
    0x00000000a74bbf35: 1.2000000000000000e+09
    0x00000000d691da00: 1.9000000000000000e+09
    0x00000000644f9787: 2.1010000000000000e+09
    0x00000000725e8066: 2.1010000000000000e+09
    0x000000007b561f45: 2.1010000000000000e+09
    0x00000000d13bd34f: 2.1010000000000000e+09
    0x00000000dcd03752: 2.1010000000000000e+09
    0x8000000000000000: 2.1010000000000000e+09

    Regions:
    -
      region: "all2all"
      hash: 0x3ddc81bf
      runtime (s): 7.90158
      count: 5
      sync-runtime (s): 5.08933
      package-energy (J): 629.447
      dram-energy (J): 65.0639
      power (W): 123.68
      frequency (%): 53.0144
      frequency (Hz): 1.1133e+09
      time-hint-network (s): 2.31212
      time-hint-ignore (s): 0.000227424
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0.000909676
      time-hint-unset (s): 0
      frequency-map: 1000000000.000000
    -
      region: "dgemm"
      hash: 0xa74bbf35
      runtime (s): 3.84953
      count: 5
      sync-runtime (s): 1.31682
      package-energy (J): 221.495
      dram-energy (J): 18.0528
      power (W): 168.204
      frequency (%): 58.7945
      frequency (Hz): 1.23468e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0.304285
      time-hint-memory (s): 0.000227384
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0.294047
      time-hint-unset (s): 0
      frequency-map: 1200000000.000000
    -
      region: "stream"
      hash: 0xd691da00
      runtime (s): 2.36882
      count: 5
      sync-runtime (s): 0.634445
      package-energy (J): 130.992
      dram-energy (J): 17.6908
      power (W): 206.466
      frequency (%): 90.7285
      frequency (Hz): 1.9053e+09
      time-hint-network (s): 0.000454914
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0.0332022
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0.254711
      time-hint-unset (s): 0
      frequency-map: 1900000000.000000
    -
      region: "model-init"
      hash: 0x644f9787
      runtime (s): 1.79939
      count: 1
      sync-runtime (s): 1.78118
      package-energy (J): 379.347
      dram-energy (J): 48.3469
      power (W): 212.975
      frequency (%): 100
      frequency (Hz): 2.10001e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0.00159183
      time-hint-compute (s): 0.000227454
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0.807783
      time-hint-unset (s): 0
      frequency-map: 2101000000.000000
    -
      region: "MPI_Barrier"
      hash: 0x7b561f45
      runtime (s): 1.47007
      count: 5
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      frequency-map: 2101000000.000000
    -
      region: "geopm_stream_model_region_startup"
      hash: 0xdcd03752
      runtime (s): 0.0535293
      count: 1
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      frequency-map: 2101000000.000000
    -
      region: "geopm_dgemm_model_region_startup"
      hash: 0xd13bd34f
      runtime (s): 0.0027099
      count: 1
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      frequency-map: 2101000000.000000
    Unmarked Totals:
      runtime (s): 0.0222825
      count: 0
      sync-runtime (s): 8.64613
      package-energy (J): 1488.02
      dram-energy (J): 151.189
      power (W): 172.102
      frequency (%): 73.3308
      frequency (Hz): 1.53995e+09
      time-hint-network (s): 1.94759
      time-hint-ignore (s): 0.0263799
      time-hint-compute (s): 0.00614051
      time-hint-memory (s): 0.00159184
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 1.93803
      time-hint-unset (s): 0.00909625
      frequency-map: 2101000000.000000
    Epoch Totals:
      runtime (s): 15.6547
      count: 5
      sync-runtime (s): 15.6547
      package-energy (J): 2463.99
      dram-energy (J): 251.396
      power (W): 157.396
      frequency (%): 69.8093
      frequency (Hz): 1.46599e+09
      time-hint-network (s): 4.26016
      time-hint-ignore (s): 0.0256979
      time-hint-compute (s): 0.304285
      time-hint-memory (s): 0.0350214
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 2.48019
      time-hint-unset (s): 0.00909625
    Application Totals:
      runtime (s): 17.4679
      count: 0
      sync-runtime (s): 17.4679
      package-energy (J): 2849.3
      dram-energy (J): 300.343
      power (W): 163.116
      frequency (%): 75.3621
      frequency (Hz): 1.5826e+09
      time-hint-network (s): 4.26016
      time-hint-ignore (s): 0.0281991
      time-hint-compute (s): 0.310653
      time-hint-memory (s): 0.0350214
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 3.29548
      time-hint-unset (s): 0.00909625
      geopmctl memory HWM (B): 45876
      geopmctl network BW (B/s): 0

```

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/pull/1536/commits/0a7592a12fc4e4a95a6b30a2cfa4bdf8202b6adc

Not sure why these tests are passing with the dev branch, but the fix above seems to account for the problem.
