### ISSUE TITLE
test_progress.py tests intermittently failing

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#1581]
First appeared:
http://mcfly.ra.intel.com/~test/cron_runs/2021-03-14_0000/test_loop_output.log

Relevant log output:
```
======================================================================
FAIL: test_linear_progress_dgemm (test_progress.TestIntegration_progress)
Test that the dgemm region with the calls to geopm_tprof_post()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_progress.py", line 261, in test_linear_progress_dgemm
    self.check_monotone(dgemm_post_df[name], err_msg)
  File "./test_progress.py", line 223, in check_monotone
    self.assertLessEqual(0, min(progress.diff()[1:]), err_msg)
AssertionError: 0 not less than or equal to -0.2499 : Bad fit for dgemm cpu 2 progress
 
======================================================================
FAIL: test_linear_progress_triad (test_progress.TestIntegration_progress)
Test that the triad region with the geopm_tprof_post() call reports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_progress.py", line 240, in test_linear_progress_triad
    self.check_monotone(triad_post_df[name], err_msg)
  File "./test_progress.py", line 221, in check_monotone
    self.assertEqual(progress[0], min(progress), err_msg)
AssertionError: 0.00112598 != 0.000261873 : Bad fit for triad cpu 2 progress
```

Relevant files:
http://mcfly.ra.intel.com/~test/cron_runs/2021-03-14_0000/test_progress*
(from mcfly) ```ls ~test/public_html/cron_runs/2021-03-14_0000/test_progress*```

It appears to have landed on ```mcfly[1,5]```.

There's suspicion around the progress data in the trace and the starting value being non-zero when a region is entered.  
Further inspection is needed.

**Comment by cmcantalupo** [comment]
Attempt to fix this issue is here:

https://github.com/cmcantalupo/geopm/tree/set-hint-with-hash
