### ISSUE TITLE
Very intermittent failure of test_progress.TestIntegration_progress

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1601]
One occurrence of this failure seen in the nightly tests.

```
======================================================================
FAIL: test_linear_progress_triad (test_progress.TestIntegration_progress)
Test that the triad region with the geopm_tprof_post() call reports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_progress.py", line 244, in test_linear_progress_triad
    err_msg)
  File "./test_progress.py", line 171, in check_progress
    self.assertLess(len(progress) * 0.6, sum(good_idx))
AssertionError: 98.39999999999999 not less than 91

----------------------------------------------------------------------
Ran 51 tests in 1660.651s
```

**Comment by cmcantalupo** [comment]
Seems like too much data is being filtered out (more than 60%) in the isnan and not-max filtering.
