### ISSUE TITLE
GEOPM service reports write lock is held when tests are run quickly back-to-back

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2005]
**Describe the bug**
I tried to run the GEOPM HPC Runtime integration tests on a system where msr-safe was enabled, but the user running the integration tests did not have permission to use the msr-save devices (see #1895).  I expected the tests to pass, and many tests did pass, however some tests failed when executed in aggregate with the other tests using the following command:

```
cd geopm/integration/test
python3 .
```

An example is the test_frequency_map.py output which presented the following errors:

```
Error: <geopm> Runtime error: SDBus: Failed to call sd-bus function sd_bus_call(), error:-5 name: not.known.Error.RuntimeError: The geopm service already has a connected "rw" mode client: at src/SDBus.cpp:59
```

This appears to kill the controller process, and the application times out at the end of the run.  

```
srun: error: mcfly1: task 0: Exited with exit code 255
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=0 : is_writer=0 : Timed out waiting for status 5: at src/ControlMessage.cpp:108
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=0 : is_writer=0 : Timed out waiting for status 5: at src/ControlMessage.cpp:108
terminate called after throwing an instance of 'geopm::Exception'
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=0 : is_writer=1 : Timed out waiting for status 5: at src/ControlMessage.cpp:108
  what():  <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=0 : is_writer=0 : Timed out waiting for status 5: at src/ControlMessage.cpp:108
```

When I executed this test in isolation it passes:

```
$ python3 test_frequency_map.py
srun: Loaded msrsave restore plugin.
srun: Loaded msrsave restore plugin.
srun: Loaded msrsave restore plugin.
srun: Loaded msrsave restore plugin.
Warning: <geopm> geopmpy.io: Trace HDF5 file not detected or older than traces.  Data will be saved to trace_338fc90b51b47725fb4f8086b7d2.h5.
/usr/lib64/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
.
----------------------------------------------------------------------
Ran 1 test in 20.171s

OK
```

**GEOPM version**
Based on the current version tracked in the `batch-server` branch which is part of PR #1998
5e73b1dacb84a33451e08f6888b49711cbfbb503

**Expected behavior**
Because the tests are run in serial, I do not expect the lock to be held by the last test when a new test starts.

**Actual behavior**
Seems as though there is a race for the GEOPM service write lock release/allocation between tests.  If tests are run quickly back to back, the lock appears to be held.  

**Error messages produced**
See above, although debug was not enabled.  Additionally a snippet of the output from `journalctl -e -u geopm` (verbose logging is used by the service in this branch, this will be changed prior to merging):

```
Nov 17 15:57:35 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 15:57:35 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 15:57:35 mcfly1 geopmd[31753]: pio.start_batch_server(): return 45328 45263
Nov 17 15:57:41 mcfly1 geopmd[31753]: pio.start_batch_server(33945, [(3, 0, 'INSTRUCTIONS_RETIRED'), (3, 1, 'INSTRUCTIONS_RETIRED'), (3, 2,>
Nov 17 15:57:41 mcfly1 geopmd[31753]: UCTIONS_RETIRED'), (3, 62, 'INSTRUCTIONS_RETIRED'), (3, 63, 'INSTRUCTIONS_RETIRED'), (3, 64, 'INSTRUC>
Nov 17 15:57:41 mcfly1 geopmd[31753]: RFCTR'), (3, 34, 'MSR::IA32_PMC0:PERFCTR'), (3, 35, 'MSR::IA32_PMC0:PERFCTR'), (3, 36, 'MSR::IA32_PMC>
Nov 17 15:57:41 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 15:57:41 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 15:57:41 mcfly1 geopmd[31753]: pio.start_batch_server(): return 45333 33945
Nov 17 15:57:47 mcfly1 geopmd[31753]: The call io.github.geopm.PlatformStartBatch has failed with an exception:
Nov 17 15:57:47 mcfly1 geopmd[31753]: Traceback (most recent call last):
Nov 17 15:57:47 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 459, in _method_callback
Nov 17 15:57:47 mcfly1 geopmd[31753]:     **additional_args
Nov 17 15:57:47 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 265, in _handle_call
Nov 17 15:57:47 mcfly1 geopmd[31753]:     return handler(*parameters, **additional_args)
Nov 17 15:57:47 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 881, in PlatformStartBatch
Nov 17 15:57:47 mcfly1 geopmd[31753]:     return self._platform.start_batch(self._get_pid(**call_info), signal_config, control_config)
Nov 17 15:57:47 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 581, in start_batch
Nov 17 15:57:47 mcfly1 geopmd[31753]:     self._write_mode(client_pid)
Nov 17 15:57:47 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 755, in _write_mode
Nov 17 15:57:47 mcfly1 geopmd[31753]:     raise RuntimeError('The geopm service already has a connected "rw" mode client')
Nov 17 15:57:47 mcfly1 geopmd[31753]: RuntimeError: The geopm service already has a connected "rw" mode client
Nov 17 15:59:24 mcfly1 geopmd[31753]: The call io.github.geopm.PlatformStartBatch has failed with an exception:
Nov 17 15:59:24 mcfly1 geopmd[31753]: Traceback (most recent call last):
Nov 17 15:59:24 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 459, in _method_callback
Nov 17 15:59:24 mcfly1 geopmd[31753]:     **additional_args
Nov 17 15:59:24 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 265, in _handle_call
Nov 17 15:59:24 mcfly1 geopmd[31753]:     return handler(*parameters, **additional_args)
Nov 17 15:59:24 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 881, in PlatformStartBatch
Nov 17 15:59:24 mcfly1 geopmd[31753]:     return self._platform.start_batch(self._get_pid(**call_info), signal_config, control_config)
Nov 17 15:59:24 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 581, in start_batch
Nov 17 15:59:24 mcfly1 geopmd[31753]:     self._write_mode(client_pid)
Nov 17 15:59:24 mcfly1 geopmd[31753]:   File "/usr/lib/python3.6/site-packages/geopmdpy/service.py", line 755, in _write_mode
Nov 17 15:59:24 mcfly1 geopmd[31753]:     raise RuntimeError('The geopm service already has a connected "rw" mode client')
Nov 17 15:59:24 mcfly1 geopmd[31753]: RuntimeError: The geopm service already has a connected "rw" mode client
Nov 17 16:00:39 mcfly1 geopmd[31753]: pio.start_batch_server(45975, [(1, 0, 'ENERGY_PACKAGE'), (1, 1, 'ENERGY_PACKAGE'), (4, 0, 'ENERGY_DRA>
Nov 17 16:00:39 mcfly1 geopmd[31753]: 4, 'CYCLES_THREAD'), (3, 75, 'CYCLES_THREAD'), (3, 76, 'CYCLES_THREAD'), (3, 77, 'CYCLES_THREAD'), (3>
Nov 17 16:00:39 mcfly1 geopmd[31753]: EFERENCE'), (3, 59, 'CYCLES_REFERENCE'), (3, 60, 'CYCLES_REFERENCE'), (3, 61, 'CYCLES_REFERENCE'), (3>
Nov 17 16:00:39 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 16:00:39 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 16:00:39 mcfly1 geopmd[31753]: pio.start_batch_server(): return 45989 45975
Nov 17 16:00:49 mcfly1 geopmd[31753]: pio.start_batch_server(46117, [(1, 0, 'ENERGY_PACKAGE'), (1, 1, 'ENERGY_PACKAGE'), (4, 0, 'ENERGY_DRA>
Nov 17 16:00:49 mcfly1 geopmd[31753]: 4, 'CYCLES_THREAD'), (3, 75, 'CYCLES_THREAD'), (3, 76, 'CYCLES_THREAD'), (3, 77, 'CYCLES_THREAD'), (3>
Nov 17 16:00:49 mcfly1 geopmd[31753]: EFERENCE'), (3, 59, 'CYCLES_REFERENCE'), (3, 60, 'CYCLES_REFERENCE'), (3, 61, 'CYCLES_REFERENCE'), (3>
Nov 17 16:00:49 mcfly1 geopmd[31753]: EQUENCY'), (3, 51, 'FREQUENCY'), (3, 52, 'FREQUENCY'), (3, 53, 'FREQUENCY'), (3, 54, 'FREQUENCY'), (3>
Nov 17 16:00:49 mcfly1 geopmd[31753]: ATURE_CORE'), (2, 43, 'TEMPERATURE_CORE')], []): begin
Nov 17 16:00:49 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 16:00:49 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 16:00:49 mcfly1 geopmd[31753]: pio.start_batch_server(): return 46158 46117
Nov 17 16:00:52 mcfly1 geopmd[31753]: pio.start_batch_server(46274, [(1, 0, 'ENERGY_PACKAGE'), (1, 1, 'ENERGY_PACKAGE'), (4, 0, 'ENERGY_DRA>
Nov 17 16:00:52 mcfly1 geopmd[31753]: 4, 'CYCLES_THREAD'), (3, 75, 'CYCLES_THREAD'), (3, 76, 'CYCLES_THREAD'), (3, 77, 'CYCLES_THREAD'), (3>
Nov 17 16:00:52 mcfly1 geopmd[31753]: EFERENCE'), (3, 59, 'CYCLES_REFERENCE'), (3, 60, 'CYCLES_REFERENCE'), (3, 61, 'CYCLES_REFERENCE'), (3>
Nov 17 16:00:52 mcfly1 geopmd[31753]: EQUENCY'), (3, 51, 'FREQUENCY'), (3, 52, 'FREQUENCY'), (3, 53, 'FREQUENCY'), (3, 54, 'FREQUENCY'), (3>
Nov 17 16:00:52 mcfly1 geopmd[31753]: ATURE_CORE'), (2, 43, 'TEMPERATURE_CORE')], []): begin
Nov 17 16:00:52 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 16:00:52 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 16:00:52 mcfly1 geopmd[31753]: pio.start_batch_server(): return 46305 46274
Nov 17 16:00:55 mcfly1 geopmd[31753]: pio.start_batch_server(46404, [(1, 0, 'ENERGY_PACKAGE'), (1, 1, 'ENERGY_PACKAGE'), (4, 0, 'ENERGY_DRA>
Nov 17 16:00:55 mcfly1 geopmd[31753]: 4, 'CYCLES_THREAD'), (3, 75, 'CYCLES_THREAD'), (3, 76, 'CYCLES_THREAD'), (3, 77, 'CYCLES_THREAD'), (3>
Nov 17 16:00:55 mcfly1 geopmd[31753]: EFERENCE'), (3, 59, 'CYCLES_REFERENCE'), (3, 60, 'CYCLES_REFERENCE'), (3, 61, 'CYCLES_REFERENCE'), (3>
Nov 17 16:00:55 mcfly1 geopmd[31753]: EQUENCY'), (3, 51, 'FREQUENCY'), (3, 52, 'FREQUENCY'), (3, 53, 'FREQUENCY'), (3, 54, 'FREQUENCY'), (3>
Nov 17 16:00:55 mcfly1 geopmd[31753]: ATURE_CORE'), (2, 43, 'TEMPERATURE_CORE')], []): begin
Nov 17 16:00:55 mcfly1 geopmd[31753]: pio.start_batch_server(): call enter
Nov 17 16:00:55 mcfly1 geopmd[31753]: pio.start_batch_server(): call exit
Nov 17 16:00:55 mcfly1 geopmd[31753]: pio.start_batch_server(): return 46425 46404
```

**Additional context**
Note this is not a bug present in the `dev` branch, but in PR #1998 which has not been merged yet.

**Comment by cmcantalupo** [comment]
This may be a test problem.  It seems that some tests are grabbing the write lock with the PID of the test harness process (the one running unittest.main()).  When this process is colocated on the same node as test processes that also need the lock, like the controller process of the runtime, the controller fails to get the write lock.  If the python script that runs the tests is executed on the head node (i.e. not within a node allocation) these tests pass.
