### ISSUE TITLE
The GEOPM SLURM Spank plugin that enforces a static policy does not work when policy is enforced through the service

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2017]
**Describe the bug**
I tried to run the test_enforce_policy.py integration test with a user that is not in the msr-safe group while the GEOPM Service is enabled and these tests fail.  The reason is because the slurm_spank_job_prolog() callback is made in the context of the user launching the job and the process that makes the call does not persist after the call completes.  For this reason, the controls are immediately reverted by the service.  

**GEOPM version**
c01721cd41558e33f71763fee34012201ffd0767

**Expected behavior**
I expected the Slurm plugin to enforce the policy even if the user must use the service to access the controls that the policy relates to.

**Actual behavior**
The integration tests fail with messages about the failure to enforce the frequency and power limits of the agent when the runtime is not being used --disable-geopm-ctl

**Error messages produced**
```
sF.FF
======================================================================
FAIL: test_freq_map_max_freq (__main__.TestIntegrationEnforcePolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test-service/geopm-cmcantal/integration/test/test_enforce_policy.py", line 149, in test_freq_map_max_freq
    self.assertEqual(test_freq, current_freq)
AssertionError: 1900000000.0 != 3700000000.0

======================================================================
FAIL: test_power_balancer_power_cap (__main__.TestIntegrationEnforcePolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test-service/geopm-cmcantal/integration/test/test_enforce_policy.py", line 185, in test_power_balancer_power_cap
    self.assertEqual(test_power, current_power)
AssertionError: 260.0 != 280.0

======================================================================
FAIL: test_power_governor_power_cap (__main__.TestIntegrationEnforcePolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test-service/geopm-cmcantal/integration/test/test_enforce_policy.py", line 173, in test_power_governor_power_cap
    self.assertEqual(test_power, current_power)
AssertionError: 260.0 != 280.0

----------------------------------------------------------------------
Ran 5 tests in 20.655s

FAILED (failures=3, skipped=1)
```

**Comment by cmcantalupo** [comment]
It is possible that the session leader of the spank plugin persists, in which case the change that ties the lock to the session leader would fix this issue.  Run test again to verify.

**Comment by cmcantalupo** [comment]
For 2.0 verify if the problem still exists.  If the problem still exists, remove spank plugin from code.
