### ISSUE TITLE
Some integration tests are failing

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2311]
**Describe the bug**
I tried to run the integration tests and I expected them to pas instead some fail.

**GEOPM version**
Tip of dev today.

**Expected behavior**
RC = 0

**Actual behavior**
```
======================================================================
ERROR: setUpClass (integration.test.test_frequency_map.TestIntegration_frequency_map)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/experiment/machine.py", line 21, in load
    with open(self.path) as fid:
FileNotFoundError: [Errno 2] No such file or directory: './machine.json'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_frequency_map.py", line 68, in setUpClass
    cls._machine.load()
  File "/home/test/geopm/integration/experiment/machine.py", line 35, in load
    raise RuntimeError("<geopm> Unable to open machine config {}.".format(self.path))
RuntimeError: <geopm> Unable to open machine config ./machine.json.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_frequency_map.py", line 71, in setUpClass
    cls._machine.save()
  File "/home/test/geopm/integration/experiment/machine.py", line 41, in save
    self._query()
  File "/home/test/geopm/integration/experiment/machine.py", line 116, in _query
    self.topo = util.geopmread_domain()
  File "/home/test/geopm/integration/experiment/util.py", line 119, in geopmread_domain
    domain, count = tuple(line.split())
ValueError: not enough values to unpack (expected 2, got 1)
 
======================================================================
ERROR: setUpClass (integration.test.test_hint_time.TestIntegration_hint_time)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/experiment/machine.py", line 21, in load
    with open(self.path) as fid:
FileNotFoundError: [Errno 2] No such file or directory: './machine.json'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_hint_time.py", line 85, in setUpClass
    cls._machine.load()
  File "/home/test/geopm/integration/experiment/machine.py", line 35, in load
    raise RuntimeError("<geopm> Unable to open machine config {}.".format(self.path))
RuntimeError: <geopm> Unable to open machine config ./machine.json.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_hint_time.py", line 87, in setUpClass
    cls._machine.save()
  File "/home/test/geopm/integration/experiment/machine.py", line 41, in save
    self._query()
  File "/home/test/geopm/integration/experiment/machine.py", line 116, in _query
    self.topo = util.geopmread_domain()
  File "/home/test/geopm/integration/experiment/util.py", line 119, in geopmread_domain
    domain, count = tuple(line.split())
ValueError: not enough values to unpack (expected 2, got 1)
 
======================================================================
ERROR: setUpClass (integration.test.test_progress.TestIntegration_progress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/experiment/machine.py", line 21, in load
    with open(self.path) as fid:
FileNotFoundError: [Errno 2] No such file or directory: './machine.json'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/experiment/machine.py", line 138, in try_machine
    mm.load()
  File "/home/test/geopm/integration/experiment/machine.py", line 35, in load
    raise RuntimeError("<geopm> Unable to open machine config {}.".format(self.path))
RuntimeError: <geopm> Unable to open machine config ./machine.json.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_progress.py", line 64, in setUpClass
    cls._machine = machine.try_machine('.', cls._test_name)
  File "/home/test/geopm/integration/experiment/machine.py", line 146, in try_machine
    mm.save()
  File "/home/test/geopm/integration/experiment/machine.py", line 41, in save
    self._query()
  File "/home/test/geopm/integration/experiment/machine.py", line 116, in _query
    self.topo = util.geopmread_domain()
  File "/home/test/geopm/integration/experiment/util.py", line 119, in geopmread_domain
    domain, count = tuple(line.split())
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by bgeltz** [comment]
The recent rename changes have caused the formatting in the main for geopmread/write to cause an issue around the parsing of `package_integrated_memory`.  Because there is no space between the domain name and the count, it's being treated as one entity that breaks the parsing in `geopmread_domain()` of `integration/experiment/util.py`.  Here's the current output:

```
$ geopmread -d
board                   1
package                 2
core                    44
cpu                     88
memory                  4
package_integrated_memory0
nic                     0
package_integrated_nic  0
gpu                     0
package_integrated_gpu  0
gpu_chip                0
```

```
$ geopmwrite -d
board                   1
package                 2
core                    44
cpu                     88
memory                  4
package_integrated_memory0
nic                     0
package_integrated_nic  0
gpu                     0
package_integrated_gpu  0
gpu_chip                0
```
