### ISSUE TITLE
Several integration tests run in the nightlies are failing

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2342]
**Describe the bug**
I tried to run the nightly integration tests and I expected them to pass instead the following test fail:

- test_tutorial_base
- test_geopmread_all_signal_agg

**GEOPM version**
Output from `geopmread --version`

445edc3

**Expected behavior**
Integration tests are expected to pass

**Actual behavior**
They fail.

**Error messages produced**
```
======================================================================
FAIL: test_geopmread_all_signal_agg (integration.test.test_geopmio.TestIntegrationGeopmio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_geopmio.py", line 119, in test_geopmread_all_signal_agg
    self.check_no_error([sig, 'board', '0'])
  File "/home/test/geopm/integration/test/test_geopmio.py", line 59, in check_no_error
    self.assertNotIn('Error', line)
AssertionError: 'Error' unexpectedly found in 'Error: cannot read signal: <geopm> Invalid argument: PlatformIOImp::read_signal(): no support for signal name "MSR::HWP_CAPABILITIES#" and domain type "1"'
```
and
```
OMP_PROC_BIND=true GEOPM_CTL=process GEOPM_PROFILE= GEOPM_REPORT=tutorial_0_report GEOPM_TRACE=tutorial_0_trace KMP_AFFINITY=disabled MV2_ENABLE_AFFINITY=0 KMP_WARNINGS=FALSE srun -N 2 -n 10 --cpu-bind v,mask_cpu:0x2,0xffc00000000ffc,0x3ff000000003ff000,0x3ff000000003ff000000,0xffc00000000ffc00000000 --export=LD_PRELOAD=libgeopm.so,ALL -- ./tutorial_0

srun: Loaded msrsave restore plugin.
cpu-bind=MASK - mcfly1, task  3  3 [39885]: mask 0x3ff000000003ff000000 set
cpu-bind=MASK - mcfly2, task  8  3 [15921]: mask 0x3ff000000003ff000000 set
cpu-bind=MASK - mcfly1, task  0  0 [39882]: mask 0x2 set
cpu-bind=MASK - mcfly2, task  9  4 [15922]: mask 0xffc00000000ffc00000000 set
cpu-bind=MASK - mcfly1, task  1  1 [39883]: mask 0xffc00000000ffc set
cpu-bind=MASK - mcfly2, task  5  0 [15918]: mask 0x2 set
cpu-bind=MASK - mcfly1, task  2  2 [39884]: mask 0x3ff000000003ff000 set
cpu-bind=MASK - mcfly2, task  6  1 [15919]: mask 0xffc00000000ffc set
cpu-bind=MASK - mcfly1, task  4  4 [39886]: mask 0xffc00000000ffc00000000 set
cpu-bind=MASK - mcfly2, task  7  2 [15920]: mask 0x3ff000000003ff000 set
Error: <geopm> File exists: SharedMemoryImp: Could not open shared memory with key /geopm-shm-1044-status: at src/SharedMemory.cpp:113
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: PlatformIOImp::restore_control(): Called prior to save_control(): at src/PlatformIO.cpp:631
Error: <geopm> Invalid argument: PlatformIOImp::signal_behavior(): unknown signal "ENERGY_PACKAGE": at src/PlatformIO.cpp:705
srun: error: mcfly1: task 0: Aborted (core dumped)
MPI_COMM_WORLD size: 8
Sleeping for five seconds
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 4774.178 ON mcfly1 CANCELLED AT 2022-05-24T19:03:08 DUE TO TIME LIMIT ***
srun: got SIGCONT
srun: forcing job termination
```

**Additional context**

**Comment by lhlawson** [comment]
Additional context:
https://github.com/geopm/geopm/pull/2341#issuecomment-1136626445
