### ISSUE TITLE
Failing integration tests with PowerGovernorAgent

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#274]
Some of the integration tests are failing when the PowerGovernorAgent is set as the agent.  These tests pass with the new code path when the MonitorAgent is chosen.

Changing the wait() method of the PowerGovernorAgent to match wait() from the MonitorAgent() does not fix this problem, so the overhead may be somewhere else.

```
======================================================================
FAIL: test_sample_rate (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./geopm_test_integration.py", line 757, in test_sample_rate
    self.assertGreater(max_mean, delta_t.mean())
AssertionError: 0.01 not greater than 0.035643613710558505

======================================================================
FAIL: test_trace_runtimes (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./geopm_test_integration.py", line 383, in test_trace_runtimes
    self.assertNear(trace_elapsed_time, region_data.get_runtime())
  File "./geopm_test_integration.py", line 127, in assertNear
    self.fail('The fractional difference between {a} and {b} is greater than {epsilon}'.format(a=a, b=b, epsilon=epsilon))
AssertionError: The fractional difference between 0.484233289 and 0.562775 is greater than 0.05
```

**Comment by dianarg** [comment]
test_trace_runtimes was fixed by 3d03aaa and e54f33f.

**Comment by dianarg** [comment]
test_sample_rate is failing on KNL because writing MSRs is slow, which causes a long delay between samples every 10 iterations.  We are currently investigating whether we can write controls to a single CPU for the whole package.

**Comment by dianarg** [comment]
https://review.gerrithub.io/#/c/geopm/geopm/+/421297/
