### ISSUE TITLE
Some regions contain invalid data when leveraging the GEOPM service

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2945]
**Describe the bug**
I tried to run `test_cpu_activity_agent.py` with the GEOPM service (and without direct access to msr-safe) and I expected the test to pass instead it failed.

**GEOPM version**
bfd90ec5a

**Expected behavior**
The integration test passes with an RC of 0.

**Actual behavior**
The test fails with the following error:
```
======================================================================
ERROR: setUpClass (integration.test.test_cpu_activity_agent.TestIntegration_cpu_activity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_cpu_activity_agent.py", line 144, in setUpClass
    0, 0, False)
  File "/home/test/geopm/integration/experiment/uncore_frequency_sweep/gen_cpu_activity_constconfig_recommendation.py", line 115, in get_config_from_frequency_sweep
    region=region_list[0], freq_col=freq_col)
  File "/home/test/geopm/integration/experiment/uncore_frequency_sweep/gen_cpu_activity_constconfig_recommendation.py", line 80, in system_memory_bandwidth_characterization
    mem_df = df.groupby(freq_col).get_group(k)
  File "/home/test/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 810, in get_group
    raise KeyError(name)
KeyError: nan
```

**Additional context**
Digging into why that error is showing up:  `gen_cpu_activity_constconfig_recommendation.py` tries to process the report data from the uncore frequency sweep with AIB.  In the cases where the test proceeds past this error because the user has direct access to msr-safe, the report data looks normal:
```
      region: "intensity_1"
      hash: 0xcf3a93bc
      runtime (s): 5.48304
      count: 5
      sync-runtime (s): 5.3522
      package-energy (J): 1328.52
      dram-energy (J): 162.476
      power (W): 248.219
      frequency (%): 99.9999
      frequency (Hz): 2.1e+09
      time-hint-network (s): 0.183821
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 5.16839
      time-hint-unset (s): 0
      time-hint-spin (s): 0
      uncore-frequency (Hz): 2.4e+09
      MSR::QM_CTR_SCALED_RATE@package-0: 1.06824e+11
      MSR::QM_CTR_SCALED_RATE@package-1: 1.11828e+11
      CPU_UNCORE_FREQUENCY_STATUS@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_STATUS@package-1: 2.4e+09
      MSR::CPU_SCALABILITY_RATIO@package-0: 0.154151
      MSR::CPU_SCALABILITY_RATIO@package-1: 0.0848756
      CPU_FREQUENCY_MAX_CONTROL@package-0: 2.1e+09
      CPU_FREQUENCY_MAX_CONTROL@package-1: 2.1e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-1: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-1: 2.4e+09
      frequency-map: 2100000000.000000
    Unmarked Totals:
      runtime (s): 0.974054
      count: 0
      sync-runtime (s): 1.10426
      package-energy (J): 288.652
      dram-energy (J): 23.2209
      power (W): 261.398
      frequency (%): 99.9995
      frequency (Hz): 2.09999e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0.131726
      time-hint-unset (s): 0.972534
      time-hint-spin (s): 0
      uncore-frequency (Hz): 2.39982e+09
      MSR::QM_CTR_SCALED_RATE@package-0: 3.06596e+10
      MSR::QM_CTR_SCALED_RATE@package-1: 2.19468e+10
      CPU_UNCORE_FREQUENCY_STATUS@package-0: 2.39982e+09
      CPU_UNCORE_FREQUENCY_STATUS@package-1: 2.3998e+09
      MSR::CPU_SCALABILITY_RATIO@package-0: 0.763355
      MSR::CPU_SCALABILITY_RATIO@package-1: 0.860866
      CPU_FREQUENCY_MAX_CONTROL@package-0: 2.1e+09
      CPU_FREQUENCY_MAX_CONTROL@package-1: 2.1e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-1: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-1: 2.4e+09
      frequency-map: 2100000000.000000
```

When the test fails and generates the `KeyError` about NaN, this is what is seen in the report for those same regions:
```
      region: "intensity_1"
      hash: 0xcf3a93bc
      runtime (s): 5.27285
      count: 5
      sync-runtime (s): 0
      package-energy (J): 0
      dram-energy (J): 0
      power (W): 0
      frequency (%): 0
      frequency (Hz): 0
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0
      time-hint-spin (s): 0
      MSR::QM_CTR_SCALED_RATE@package-0: nan
      MSR::QM_CTR_SCALED_RATE@package-1: nan
      CPU_UNCORE_FREQUENCY_STATUS@package-0: nan
      CPU_UNCORE_FREQUENCY_STATUS@package-1: nan
      MSR::CPU_SCALABILITY_RATIO@package-0: nan
      MSR::CPU_SCALABILITY_RATIO@package-1: nan
      CPU_FREQUENCY_MAX_CONTROL@package-0: nan
      CPU_FREQUENCY_MAX_CONTROL@package-1: nan
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-0: nan
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-1: nan
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-0: nan
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-1: nan
    Unmarked Totals:
      runtime (s): -5.65483
      count: 0
      sync-runtime (s): 0.0241354
      package-energy (J): 4.70264
      dram-energy (J): 0.422684
      power (W): 194.844
      frequency (%): 99.9822
      frequency (Hz): 2.09963e+09
      time-hint-network (s): 0
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 0
      time-hint-unset (s): 0.0241669
      time-hint-spin (s): 0
      uncore-frequency (Hz): 2.4e+09
      MSR::QM_CTR_SCALED_RATE@package-0: 0
      MSR::QM_CTR_SCALED_RATE@package-1: 0
      CPU_UNCORE_FREQUENCY_STATUS@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_STATUS@package-1: 2.4e+09
      MSR::CPU_SCALABILITY_RATIO@package-0: 0.585075
      MSR::CPU_SCALABILITY_RATIO@package-1: 0.613099
      CPU_FREQUENCY_MAX_CONTROL@package-0: 2.1e+09
      CPU_FREQUENCY_MAX_CONTROL@package-1: 2.1e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MIN_CONTROL@package-1: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-0: 2.4e+09
      CPU_UNCORE_FREQUENCY_MAX_CONTROL@package-1: 2.4e+09
      frequency-map: 2100000000.000000
```

It seems like the data that should have been attributed to region "intensity_1" is instead going to "Unmarked".  "intensity_1" should have run for just over 5 seconds, and I see the "Unmarked" runtime is near that, but negative.  Not sure what to make of this yet.

Note that if I modify the integration test to run these regions in a different order, the problem goes away.  It will reproduce 100% of the time with the default ordering.

**Comment by bgeltz** [comment]
I'm going to temporarily workaround this behavior on the dev branch by changing the test around to run the longer region first.  In testing when this was reproducing, this makes the reporting issue go away.

I also tested this on the non-MPI branch, and verified that the reports come out as expected (without any hacky workarounds).  There are some changes that will have to be made in order to fix this behavior on that branch:
#2950 
#2951
