### ISSUE TITLE
Python agents are not working after non-MPI support branch merged

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2995]
**Describe the bug**
I tried to create a report with the python agent tutorial and I expected correct data instead all fields were zero.

When using the python agents, it is recommended that the [legacy-dev](https://github.com/geopm/geopm/tree/legacy-dev) branch be used until this issue is resolved in the dev branch.

**GEOPM version**
28e1581c5b2df12bc2ab7404a2d03f386ff7ff46

**Expected behavior**
No regressions in test_tutorial_python_agents.py assertions

**Actual behavior**
Test is failing and report has no timing or sampled data.

**Error messages produced**

```
======================================================================
FAIL: test_frequency_limit_report (integration.test.test_tutorial_python_agents.TestIntegration_tutorial_python_agents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_tutorial_python_agents.py", line 91, in test_frequency_limit_report
    places=0)
AssertionError: 5 != 0 within 0 places

======================================================================
FAIL: test_monitor_report (integration.test.test_tutorial_python_agents.TestIntegration_tutorial_python_agents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_tutorial_python_agents.py", line 64, in test_monitor_report
    places=0)
AssertionError: 5 != 0 within 0 places

======================================================================
FAIL: test_package_energy_report (integration.test.test_tutorial_python_agents.TestIntegration_tutorial_python_agents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/integration/test/test_tutorial_python_agents.py", line 74, in test_package_energy_report
    places=0)
AssertionError: 5 != 0 within 0 places

```

**Additional information**
When bug is fixed, please also revert skip decorator added here:
b2628e82bd6a835c7076d4f98fa6dc45bbb41efc

**Comment by cmcantalupo** [comment]
Python agent feature is removed for 3.0 release.  May take a different form in future release now that non-MPI applications are supported by the C++ runtime.
