### ISSUE TITLE
geopm_[read | write] integration tests broken after dc5dd54c.

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#391]
Error output:
======================================================================
FAIL: test_geopmread_command_line (__main__.TestIntegrationGeopmio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./geopm_test_integration.py", line 1232, in test_geopmread_command_line
    'board_accelerator', 'package_accelerator'])
  File "./geopm_test_integration.py", line 1203, in check_output
    self.assertIn(exp, line)
AssertionError: 'board' not found in 'Warning: <geopm> Environment::check(): Incompatible CPU frequency driver detected (intel_pstate). The "acpi-cpufreq" driver is required.  If this driver is not used performance may be impacted by the incompatible driver setting low frequencies when system load is low.\n'

======================================================================
FAIL: test_geopmwrite_command_line (__main__.TestIntegrationGeopmio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./geopm_test_integration.py", line 1258, in test_geopmwrite_command_line
    'board_accelerator', 'package_accelerator'])
  File "./geopm_test_integration.py", line 1203, in check_output
    self.assertIn(exp, line)
AssertionError: 'board' not found in 'Warning: <geopm> Environment::check(): Incompatible CPU frequency driver detected (intel_pstate). The "acpi-cpufreq" driver is required.  If this driver is not used performance may be impacted by the incompatible driver setting low frequencies when system load is low.\n'

----------------------------------------------------------------------

**Comment by bakerbrandond** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/431695
