### ISSUE TITLE
geopmanalysis ImportError

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#770]
geopmanalysis fails when importing geopmpy.io:

```
> geopmanalysis
Traceback (most recent call last):
  File "/home/drguttma/build/geopm_work/bin/geopmanalysis", line 35, in <module>
    import geopmpy.analysis
  File "/home/drguttma/build/geopm_work/lib/python2.7/site-packages/geopmpy/analysis.py", line 50, in <module>
    import geopmpy.io
  File "/home/drguttma/build/geopm_work/lib/python2.7/site-packages/geopmpy/io.py", line 39, in <module>
    from builtins import str
ImportError: No module named builtins
```

**Comment by cmcantalupo** [comment]
May no longer be an issue, also this is related to python 2/3 issues.
