### ISSUE TITLE
Fix controller handling of signals

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#773]
The Controller should gracefully exit on all nodes where it is running when it is sent a signal requiring it to do so.  Presently this is only working for the root Controller.  Tree and leaf Controllers persist and do not restore the MSR state to what it was prior to job launch.

In test_integration/geopm_test_integration.py: TestIntegration.test_controller_signal_handling() a bug is currently exposed that illustrates the issue.  The test starts a simple app (sleep for 30 seconds) on 4 nodes with the controller launched in application mode.  After 15 seconds, a a signal is sent to the Controller on every node (via a second process) to send a signal 15 (TERM).  The intention is to trigger the Controller's signal handler to gracefully shut the controller down and clean up any modified MSRs.

What's happening instead is the following:
1. At test startup, the Controller sets an initial power cap < TDP.  The test starts normally, and hangs when it is waiting for all Controller processes to finish.
2. SSH'ing into the first node in the allocation (where the root controller runs) and attempting to `pgrep -al geopm` shows **no running processes**, however the power cap has **not** been restored to TDP.
3. SSH'ing into the second node shows the Controller is still running (even though it was sent SIGTERM).  Breaking into it with gdb shows it is stuck here:
```
#0  0x00007f816df356cb in ips_ptl_poll () from /lib64/libpsm2.so.2
#1  0x00007f816df333af in psmi_poll_internal () from /lib64/libpsm2.so.2
#2  0x00007f816df2cbd5 in psm2_mq_ipeek2 () from /lib64/libpsm2.so.2
#3  0x00007f8172912f53 in psm_progress_wait (blocking=39011008) at src/mpid/ch3/channels/psm/src/psm_queue.c:247
#4  0x00007f81728eab32 in wait_progress_engine () at ./src/mpid/ch3/include/mpidrma.h:1342
#5  MPID_Win_unlock (dest=39011008, win_ptr=0x0) at src/mpid/ch3/src/ch3u_rma_sync.c:1647
#6  0x00007f817284e9e2 in PMPI_Win_unlock (rank=39011008, win=0) at src/mpi/rma/win_unlock.c:101
#7  0x00007f8172fc6cee in geopm::CommWindow::unlock (this=0x25342c0, rank=0) at src/MPIComm.cpp:434
#8  0x00007f8172fbed76 in geopm::TreeCommLevelImp::send_up (this=0x25342c0, sample=<error reading variable: Cannot access memory at address 0x8>) at src/TreeCommLevel.cpp:96
#9  0x00007f8172fbda6c in geopm::TreeCommImp::send_up (this=0x25342c0, level=0, sample=<error reading variable: Cannot access memory at address 0x2e5429>)
    at src/TreeComm.cpp:167
#10 0x00007f8172f05ddc in geopm::Controller::walk_up (this=0x25342c0) at src/Controller.cpp:459
#11 0x00007f8172f059e7 in geopm::Controller::step (this=0x25342c0) at src/Controller.cpp:395
#12 0x00007f8172f05802 in geopm::Controller::run (this=0x25342c0) at src/Controller.cpp:358
#13 0x00007f8172f08e4e in geopm_run_imp (ctl=<optimized out>) at src/Controller.cpp:122
#14 geopm_ctl_run (ctl=0x25342c0) at src/Controller.cpp:132
#15 0x00007f8172f06d6c in geopmctl_main () at src/Controller.cpp:96
#16 0x00000000004027b3 in main (argc=1, argv=0x7ffc4dca30b8) at src/geopmctl_main.c:134
```
4. SSH'ing into the third and fourth nodes show the Controller is stuck in the same spot on those nodes.
5. All 4 nodes still have a modified power cap.
6. When the test times out (after 10 minutes), SLURM will send all remaining Controller processes a SIGKILL.  The controllers on the second through fourth nodes do die.
7. Re-examining the power cap at this point shows that it **has** been restored on the first node (where the Controller did exit after the initial SIGTERM) but not on the other nodes.
8. Any other jobs run on the allocation at this point will not have a clean state of the MSRs.

It's interesting to note that the restore of the MSRs on the first node in the allocation seems to happen only **after** the Controllers on the other nodes were SIGKILL'd.  It seems as though the code to handle the SIGTERM on the first node persists after pgrep indicates that the Controller is gone on that node (?!?).

The test is not strict enough to notice that the MSRs were not restored properly.  This is described in #761.  The bigger problem is bringing down the Controller gracefully on all nodes.

The tree and leaf Controllers are in deadlock after the root Controller dies (as shown by the call stack above).  We need to figure out how to gracefully abort when this occurs.

Some useful commands to repro:
```
# Run the test
GEOPM_RUN_LONG_TESTS=true ./geopm_test_integration.py -v TestIntegration.test_controller_signal_handling

# Check the power cap
pdsh -w mcfly[5-7,15] '~/build/msr-tools/bin/rdmsr 0x610' | dshbak -c
```

**Comment by sidjana** [comment]
Close. Will not-fix.
