### ISSUE TITLE
Integration tests missing ALPS support

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#802]
Some recently added/altered integration tests are missing support for ALPS:

```
64:test_agent_energy_efficient (test_integration.geopm_test_integration.TestIntegration) ... skipped 'Requires SLURM batch session.'
111:test_power_balancer (test_integration.geopm_test_integration.TestIntegration) ... skipped 'Requires SLURM batch session.'
132:test_report_and_trace_generation_application (test_integration.geopm_test_integration.TestIntegration) ... skipped 'ALPS does not support multi-application launch on the same nodes.'
133:test_report_and_trace_generation_pthread (test_integration.geopm_test_integration.TestIntegration) ... skipped 'This test only enabled on known working systems.'
134:test_report_generation_all_nodes (test_integration.geopm_test_integration.TestIntegration) ... skipped "Requires non-sbatch SLURM session for alloc'd and idle nodes."
166:test_geopmread_all_signal_agg (test_integration.geopm_test_integration.TestIntegrationGeopmio) ... skipped 'Requires SLURM batch session.'
169:test_geopmread_signal_value (test_integration.geopm_test_integration.TestIntegrationGeopmio) ... skipped 'Requires SLURM batch session.'
171:test_geopmwrite_set_freq (test_integration.geopm_test_integration.TestIntegrationGeopmio) ... skipped 'Requires SLURM batch session.'
```

Per the investigation in #772:

> These are all expected at the moment. I have a branch on my fork where I've been working on trying to run the skipped tests and have been making headway. The work is on the bgeltz-theta-tests branch here:
https://github.com/bgeltz/geopm/tree/bgeltz-theta-tests

>The batch test decorator is specific to SLURM, which is why you see so many tests skipped because of it. There's a patch on my fork to add ALPS support (23c45ce). Running with that patch, and you'll get the next set of problems:

>The geopmread/write tests are skipped because they're trying to execute the geopmread/write binaries on the MOM nodes. They should be attempting this through the launcher instead of directly from the test code to ensure this happens on compute nodes. The tools work OK on the computes, the test code just needs to be updated.

>test_report_and_trace_generation_pthread should work with ALPS. I'll try to update the test decorator and re-run.

>test_power_balancer fails because it has a recently added dependency on getting the allocated nodes for the job, but that dependency was only coded up for SLURM. ALPS support is available, and needs to be added. Also, as it is coded the function is not returning the information the test is expecting. It's providing the test with all the allocated nodes for the cluster, not just the allocated nodes for the job. This also must be fixed.

>test_agent_energy_efficient needs to be re-evaluated with these fixes as well.

**Comment by bgeltz** [comment]
With 89f8c80a468163722fbe38c4772e625c3cf677f5, I'm down to 2 failed tests:

```
======================================================================
ERROR: test_power_balancer (test_integration.geopm_test_integration.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lus/theta-fs0/projects/intel/geopm-home/bgeltz/geopm/test_integration/geopm_test_integration.py", line 785, in test_power_balancer
    alloc_nodes = geopm_test_launcher.TestLauncher.get_alloc_nodes()
  File "/lus/theta-fs0/projects/intel/geopm-home/bgeltz/geopm/test_integration/geopm_test_launcher.py", line 238, in get_alloc_nodes
    return launcher.get_alloc_nodes()
  File "/lus/theta-fs0/projects/intel/geopm-home/bgeltz/geopm/scripts/geopmpy/launcher.py", line 824, in get_alloc_nodes
    raise NotImplementedError('Idle nodes feature requires use with SLURM')
NotImplementedError: Idle nodes feature requires use with SLURM

======================================================================
FAIL: test_geopmwrite_set_freq (test_integration.geopm_test_integration.TestIntegrationGeopmio)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lus/theta-fs0/projects/intel/geopm-home/bgeltz/geopm/test_integration/geopm_test_integration.py", line 1454, in test_geopmwrite_set_freq
    self.assertEqual(min_freq, result)
AssertionError: 1000000000.0 != 1400000000.0

----------------------------------------------------------------------
```

The power_balancer test needs to be altered such that it actually gets the nodes in the job's allocation.  The way it's currently coded, the method it calls in the launcher gets all of the idle nodes for the whole cluster.  This will cause issues if more than one job is running on the cluster.  This is the current state of SLURM support.

ALPS support for this test is non-existent.

The set_freq test is actually passing, but fails when run in a batch script because the test does not force the same node to be used for all geopm read/write calls.

**Comment by bgeltz** [comment]
Opened #868 to track the changes to the alloc_nodes query and test_power_balancer.
