### ISSUE TITLE
ronn files not getting copied into build tree

### ISSUE THREAD

**Issue by rountree** [geopm/geopm#820]
i created ``build`` and ``install`` directories inside the ``geopm`` source tree.  After running ``autogen.sh`` in the source directory and ``configure`` in the build directory, I'm hitting the following error during the execution of ``make``.

```
mkdir -p man
export GEM_PATH=`readlink -f ../ruby`:$GEM_PATH && \
cd ronn && \
../ruby/bin/ronn --date=`date "+%Y-%m-%d"` \
                 --organization="GEOPM 1.1.0+dev12gd32094ef" \
                 `basename man/GEOPM_CXX_MAN_Agent.3`.ronn
Traceback (most recent call last):
	6: from ../ruby/bin/ronn:150:in `<main>'
	5: from ../ruby/bin/ronn:150:in `map'
	4: from ../ruby/bin/ronn:150:in `block in <main>'
	3: from ../ruby/bin/ronn:150:in `new'
	2: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:75:in `initialize'
	1: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:72:in `block in initialize'
/usr/lib/ruby/vendor_ruby/ronn/document.rb:72:in `read': No such file or directory @ rb_sysopen - GEOPM_CXX_MAN_Agent.3.ronn (Errno::ENOENT)
Makefile:5584: recipe for target 'man/GEOPM_CXX_MAN_Agent.3' failed
make[1]: *** [man/GEOPM_CXX_MAN_Agent.3] Error 1
make[1]: Leaving directory '/home/rountree/llnl/geopm/build'
Makefile:2284: recipe for target 'all' failed
make: *** [all] Error 2
```
The ``ronn`` directory looks like this:
````
rountree@Solvent:~/llnl/geopm/build$ ls ronn
geopm.7  geopm.7.html  geopm.7.ronn
````
The ``man/GEOPM_CXX_MAN_Agent.3`` file exists in the source tree.  Looks like the ronn files are not getting copied over into the build tree.  Copying the files over manually allows the build to complete without error.

**Comment by cmcantalupo** [comment]
related to #3
